title: Blogs by Sagnik
author: GitHub User
email: meshagy18@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Yearned software developer & coding enthusiast. 
  Trying to automate my life 1% at a time and also help new learners as much as possible. 
  Runs a Youtube channel.
  
# social links
twitter_username: sagnik_20 # DO NOT include the @ character, or else the build will fail!
github_username:  sagnik20 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
